version: '2'
services:
  ipfs:
    container_name: "ipfs"
    restart: always
    expose:
    - 4001
    - 8080
    ports:
    - 4001:4001
    - 5001:5001
    - 8080:8080
    image: ipfs/go-ipfs
    volumes:
      - ~/.ipfs/:/data/ipfs/
